# GitHub Sponsors
github: EfficientAI-tech

# Open source collective for grants & donations
open_collective: efficientai

# Direct contact for grants, sponsorships, and institutions
custom:
  - https://efficientai.cloud/funding
  - mailto:tejas@efficientai.cloud
  - mailto:aadhar@efficientai.cloud
