global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]
        labels:
          service: "efficientai-api"

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
        labels:
          service: "efficientai-db"

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
        labels:
          service: "efficientai-redis"

  - job_name: "celery"
    static_configs:
      - targets: ["celery-exporter:9808"]
        labels:
          service: "efficientai-worker"
